In [1]:
import numpy as np
import pandas as pd

### Data Loading & Path Resolution
* **Relative Path (`..`)**: The `..` syntax tells Python to look **one folder level up** from where this notebook is saved, allowing us to access the CSV file outside our current directory.
* **Index Column Selection (`index_col=movieId`)**: The CSV contains a pre-existing index as its first column. Setting `index_col=movieId` tells pandas to use that column instead of generating a duplicate, default numeric index.

In [ ]:
movies=pd.read_csv('../movies.csv',index_col='movieId') 
movies.head()

,title,genres
movieId,,
1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
2,Jumanji (1995),Adventure|Children|Fantasy
3,Grumpier Old Men (1995),Comedy|Romance
4,Waiting to Exhale (1995),Comedy|Drama|Romance
5,Father of the Bride Part II (1995),Comedy

I assumed the csv contained columns like title, director,published date ,genre. But reading csv file by pd.read_csv helped me know what things the csv file contained.

#### How many columns are there? and what are they?

In [17]:
movies.shape

(9742, 2)

In [16]:
movies.columns

Index(['title', 'genres'], dtype='str')

.shape helped me get number of columns and rows but i noticed since i kept movieId as Index column , it didnt get count as column.

#### What does each column seem to represent?
->column title represents the Movie Title along with published date.
->column genre represents what kind of movie it is.

#### Pick one movie from the table.What is its movieId, title, and genre?

In [14]:
movies.loc[[2]]

                  title                      genres
movieId
2        Jumanji (1995)  Adventure|Children|Fantasy

Here wrapping 2 in double [] brackets forces pandas to keep the dataframe structure(tabular) which will include the movieId without the double bracket pandas will treat it as a series ecluding the structure.
To see how it will look as a series structure run the code: movies.loc[2]

In [3]:
ratings=pd.read_csv('../ratings.csv')

#### What columns do you see? What do you think each one means?

In [25]:
ratings.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

I can see 4 columns:
uderId: representing users 1 means user 1 , 2 means uder 2 and so on
movieId: representing each movie 
timestamp:Timestamps represent seconds since midnight Coordinated Universal Time (UTC) of January 1, 1970.

#### How many different users exist?

In [5]:
print(ratings["userId"].nunique())

610